services:
    _instanceof:
        Contao\CoreBundle\Framework\FrameworkAwareInterface:
            calls:
                - ["setFramework", ["@contao.framework"]]

        Symfony\Component\DependencyInjection\ContainerAwareInterface:
            calls:
                - ["setContainer", ["@service_container"]]
    EuF\ContaoNewsMeta\Classes\NewsMeta:
        class: EuF\ContaoNewsMeta\Classes\NewsMeta
        tags:
            - { name: contao.hook, hook: generatePage }